version: 2
updates:
  # Maintain dependencies for the main project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "branch-v2"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"

  # Maintain dependencies for Cloud Functions
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    target-branch: "branch-v2"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "branch-v2"
    open-pull-requests-limit: 10
    labels:
      - "ci"
